### ISSUE TITLE
[Bug] Have a coupon code are not clickable on Serbian language

### ISSUE THREAD

**Issue by evilmc** [FOSSBilling/locale#215]
### Describe the bug

**Have a coupon code?** On cart page, this string are not clickable on Serbian language. It's not possible to click to show form. When I switch on English, form works.

### How to reproduce

Go to in Fronted, select product and go to Cart and select language:  Српски(sr_RS)

### Expected behavior

When I click on [Have a coupon code?], form need to be show.

### FOSSBilling version

0.6.1

### Device

Desktop

### Information

Browser: FireFox

**Comment by BelleNottelling** [comment]
That's happening because of a QC issue with whomever translated the "You logged in successfully" string for the Serbian language.
I've fixed the problematic string in that language as well as the folder name for it.

To fix it now, you'll have to manually update the translation source from the locale repository which can be done by downloading this zip and extracting it into the `locale` directory, overwriting any existing files. You'll also want to manually delete the old "srp" folder from the same directory to prevent having two entries for this language.

https://github.com/FOSSBilling/locale/releases/download/latest/translations.zip
